spring:
  application:
    name: server-zuul
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/work_space_4
        username: jess.zhong
        password: jess
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
redis:
  database: 0
  host: 127.0.0.1
  password:
  port: 6379
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
  timeout: 0
  data-timeout: 600
eureka:
  #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
  # 告知服务端15秒还未收到心跳的话，就将该服务移除列表
  #默认90s
  instance:
    lease-expiration-duration-in-seconds: 15
  #服务刷新时间配置，每隔这个时间会主动心跳一次,每隔5s发送一次心跳
  #默认30s
  lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/
zuul:
  prefix: /jess
 # 禁止服务自动添加
  ignoredServices: '*'
  routes:
    会员系统:
      path: /member/**
      serviceId: server-member
    订单系统:
      path: /order/**
      serviceId: server-order
  max:
    host:
      connections: 60000
  #超时设置
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 300000
# 日志配置
logging:
#  file: /home/springCloud/log/jess.log  #日志输出目录--linux环境
  file: E:\workSpaces\work_space_4\logs\server-zuul\zuul.log  #日志输出目录--本地环境
  level:
      # com.jess包下所有class以DEBUG级别输出
      com.jess: DEBUG
      # root日志以WARN级别输出
      root: WARN
      org:
        springframework:
          web: DEBUG
#server-zuul:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
