server:
  port: 8001
spring:
  application:
    name: server-zuul
eureka:
  #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
  # 告知服务端15秒还未收到心跳的话，就将该服务移除列表
  #默认90s
  instance:
    lease-expiration-duration-in-seconds: 15
  #服务刷新时间配置，每隔这个时间会主动心跳一次,每隔5s发送一次心跳
  #默认30s
  lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://server1:8101/eureka/
zuul:
  prefix: /jess
 # 禁止服务自动添加
  ignoredServices: '*'
  routes:
    server-member:
          path: /member/**
    server-order:
      path: /order/**
  max:
    host:
      connections: 200
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
