spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/work_space_4
    username: jess.zhong
    password: jess
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
redis:
  database: 0
  host: 127.0.0.1
  password:
  port: 6379
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
  timeout: 0
  data-timeout: 600
zuul:
  prefix: /jess
 # 禁止服务自动添加
  ignoredServices: '*'
  routes:
    公共系统:
      path: /common/**
      serviceId: server-common
    会员系统:
      path: /member/**
      serviceId: server-member
    订单系统:
      path: /order/**
      serviceId: server-order
# 日志配置
logging:
  file: /home/springCloud/log/jess.log  #日志输出目录
  level:
    com.jess: DEBUG     # com.jess包下所有class以DEBUG级别输出
    root: WARN    # root日志以WARN级别输出
    org:
      springframework:
        web: DEBUG
