spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.65.135:3306/demo_db1
    username: root
    password: jess.zhong
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
redis:
  cluster:
    commandTimeout: 6000    # 执行命令超时时间
    max-attempts: 5   # 重试次数
    max-redirects: 3 # 跨集群执行命令时要遵循的最大重定向数量
    max-active: 16    # 连接池最大连接数（使用负值表示没有限制）
    max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 8     # 连接池中的最大空闲连接
    min-idle: 0     # 连接池中的最小空闲连接
    test-on-borrow: true    # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384   # 各 Redis 节点信息
zuul:
  prefix: /jess
 # 禁止服务自动添加
  ignoredServices: '*'
  routes:
    公共系统:
      path: /common/**
      serviceId: server-common
    会员系统:
      path: /member/**
      serviceId: server-member
    订单系统:
      path: /order/**
      serviceId: server-order
# 日志配置
logging:
  file: \springcloud\logs\server-zuul\zuul.log  #日志输出目录
  level:
    com.jess: DEBUG     # com.jess包下所有class以DEBUG级别输出
    root: WARN    # root日志以WARN级别输出
    org:
      springframework:
        web: DEBUG
