##注册中心服务端口
server:
  port: 8102
#在默认设置下，eureka的服务注册中心也会将自己作为客户端注册自己，可以在application.properties配置文件中禁用这个功能
eureka:
  instance:
    hostname: server2
##false表示不向注册中心注册自己
  client:
    #register-with-eureka: false
##注册中心的任务是维护服务，不需要检测服务，设为false
    #fetch-registry: false
    service-url:
      defaultZone: http://server1:8101/eureka/