server:
  port: 9900
  tomcat:
    max-threads: 50
spring:
  application:
    name: server-order-fegin
eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
            thread:
             timeoutInMilliseconds: 2000

