#服务端口
server:
  port: 8010
#服务名称
spring:
  application:
    name: server-config
  cloud:
    config:
      label: master
      server:
        git:
          uri:  https://github.com/zhongxuexi/DemoSpringCloud.git
          search-paths: spring-cloud-repo/**
#          username: zhongxuexi
#          password: ***
          force-pull: true
          basedir: C:\springcloud\config_repository
eureka:
  lease-renewal-interval-in-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
  client:
    service-url:
      defaultZone: http://192.168.65.131:8000/eureka/