server:
  port: 8010
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        native:
          search-locations: E:/workSpaces/work_space_4/DemoSpringCloud/spring-cloud-repo/src/resources/local-repo
eureka:
  lease-renewal-interval-in-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    registry-fetch-interval-seconds: 40