#服务端口
server:
  port: 8010
#服务名称
spring:
  application:
    name: server-config
  cloud:
    config:
      label: master
      server:
        git:
          uri:  https://github.com/zhongxuexi/DemoSpringCloud.git
          search-paths: spring-cloud-repo/**
#          username: zhongxuexi
#          password: ***
          force-pull: true
          basedir: \springcloud\config_repository
#服务注册中心
eureka:
  lease-renewal-interval-in-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    registry-fetch-interval-seconds: 40