web:
  #upload-path: ./server-member/src/main/resources/static/upload/
  upload-path: E:\workSpaces\work_space_4\upload
spring:
  profiles:
    active: member1
  application:
    name: server-member
    resources:
        static-locations: classpath:/resources/,classpath:/static/,file:${web.upload-path}
    mvc:
      static-path-pattern: /**
  ### FreeMarker 配置
  freemarker:
      allow-request-override: false
      #Enable template caching.启用模板缓存。
      cache: false
      check-template-location: true
      charset: UTF-8
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      template-loader-path: classpath:/templates/
      #设置面板后缀
      suffix: .html
#eureka:
#  client:
#    service-url:
#      defaultZone: http://server1:8001/eureka/
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/work_space_4?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  username: jess.zhong
  password: jess
#mybatis
mybatis-config-file: mybatis-config.xml
mapper-path: /mapper/**/**.xml
entity-package: com.jsee.entity

#分页
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql
# 日志配置
logging:
  file: /home/springCloud/log/jess.log  #日志输出目录
  level:
      # com.jess包下所有class以DEBUG级别输出
      com.jess: DEBUG
      # root日志以WARN级别输出
      root: WARN
      org:
        springframework:
          web: DEBUG