web:
##本地环境
  upload-path: E:\workSpaces\work_space_4\upload_file\
  upload-url: http://localhost:9001/file
#linux环境
#  upload-path: /home/springCloud/upload_file/
#  upload-url: http://192.168.0.188:8080/file
eureka:
  client:
    service-url:
      defaultZone: http://server1:8101/eureka/
spring:
  profiles:
    active: member1
  application:
    name: server-member
  http:
    multipart:
      maxFileSize: 5Mb
      maxRequestSize: 5Mb
  rabbitmq:
      host: 127.0.0.1
      port: 5672
#      username: jess.zhong
#      password: Zxx@!@686988
      username: guest
      password: guest
  datasource:
    db1:
      name: mysql1
      url: jdbc:mysql://127.0.0.1:3306/work_space_4
      username: jess.zhong
      password: jess
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    db2:
      name: mysql2
      #url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
      url: jdbc:mysql://127.0.0.1:3306/work_space_1
      username: jess.zhong
      password: jess
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

#mybatis&&通用Mapper
mybatis:
  type-aliases-package: com.jess.entity
  mapper-locations: classpath:mapper/**/**.xml

#分页
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: true
    params: count=countSql
redis:
  database: 0
  host: 127.0.0.1
  password:
  port: 6379
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
  timeout: 0
  data-timeout: 600
# 日志配置
logging:
#  file: /home/springCloud/log/jess.log  #日志输出目录--linux环境
#  file: E:\workSpaces\work_space_4\logs\jess.log  #日志输出目录--本地环境
  level:
      # com.jess包下所有class以DEBUG级别输出
      com.jess: DEBUG
      # root日志以WARN级别输出
      root: WARN
      org:
        springframework:
          web: DEBUG
management:
  security:
    enabled: false
