web:
  #linux环境
  upload-path: /home/springcloud/upload_file/
  upload-url: http://192.168.0.188:8080/file
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期
  http:
    multipart:
      maxFileSize: 5Mb
      maxRequestSize: 5Mb
  rabbitmq:
      host: 127.0.0.1
      port: 5672
#      username: jess.zhong
#      password: Zxx@!@686988
      username: guest
      password: guest
  datasource:
    default:
      name: mysql1
      url: jdbc:mysql://127.0.0.1:3306/work_space_4
      username: jess.zhong
      password: jess
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    master:
      name: mysql2
      #url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
      url: jdbc:mysql://127.0.0.1:3306/work_space_1
      username: jess.zhong
      password: jess
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql
redis:
  cluster:
    commandTimeout: 6000    # 执行命令超时时间
    max-attempts: 5   # 重试次数
    max-redirects: 3 # 跨集群执行命令时要遵循的最大重定向数量
    max-active: 16    # 连接池最大连接数（使用负值表示没有限制）
    max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 8     # 连接池中的最大空闲连接
    min-idle: 0     # 连接池中的最小空闲连接
    test-on-borrow: true    # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384   # 各 Redis 节点信息
# 日志配置
logging:
  file: /home/springCloud/log/jess.log  #日志输出目录
  level:
    com.jess: DEBUG     # com.jess包下所有class以DEBUG级别输出
    root: WARN       # root日志以WARN级别输出
    org:
      springframework:
          web: DEBUG
